== Appendix

===  Db2 Sample Tables
(((Db2 sample tables)))
Sample table DDL follows.

====  ACT

.ACT sample table – DDL
[source,sql]
....
CREATE TABLE ACT
( ACTNO   SMALLINT     NOT NULL
, ACTKWD  CHARACTER(6) NOT NULL
, ACTDESC VARCHAR(20)  NOT NULL)
IN USERSPACE1;

ALTER TABLE ACT
  ADD CONSTRAINT PK_ACT PRIMARY KEY (ACTNO);

CREATE UNIQUE INDEX XACT2 
ON ACT(ACTNO ASC, ACTKWD ASC)
ALLOW REVERSE SCANS;
....

====  CATALOG

.CATALOG sample table – DDL
[source,sql]
....
CREATE TABLE CATALOG
( NAME VARCHAR(128) NOT NULL
, CATLOG XML)
IN IBMDB2SAMPLEXML;

ALTER TABLE CATALOG
ADD CONSTRAINT PK_CATALOG PRIMARY KEY (NAME);
....

====  CL_SCHED

.CL_SCHED sample table – DDL
[source,sql]
....
CREATE TABLE CL_SCHED
( CLASS_CODE CHARACTER(7)
, DAY        SMALLINT
, STARTING   TIME
, ENDING     TIME)
IN USERSPACE1;
....

====  CUSTOMER

.CUSTOMER sample table – DDL
[source,sql]
....
CREATE TABLE CUSTOMER
( CID BIGINT NOT NULL
, INFO XML
, HISTORY XML)
IN IBMDB2SAMPLEXML;

ALTER TABLE CUSTOMER
ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY(CID);
....

====  DATA_FILE_NAMES

.DATA_FILE_NAMES sample table – DDL
[source,sql]
....
CREATE TABLE DATA_FILE_NAMES
( DATA_FILE_NAME VARCHAR(40)   NOT NULL
, DB2_TABLE_NAME VARCHAR(40)   NOT NULL
, EXPORT_FILE_NAM CHARACTER(8) NOT NULL)
IN IBMDB2SAMPLEREL;
....

====  DEPARTMENT

.DEPARTMENT sample table – DDL
[source,sql]
....
CREATE TABLE DEPARTMENT
( DEPTNO   CHARACTER(3) NOT NULL
, DEPTNAME VARCHAR(36)  NOT NULL
, MGRNO    CHARACTER(6)
, ADMRDEPT CHARACTER(3) NOT NULL
, LOCATION CHARACTER(16))
IN USERSPACE1;

ALTER TABLE DEPARTMENT
ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DEPTNO);

CREATE INDEX XDEPT2
ON DEPARTMENT(MGRNO ASC)
ALLOW REVERSE SCANS;

CREATE INDEX XDEPT3
ON DEPARTMENT(ADMRDEPT ASC)
ALLOW REVERSE SCANS;

CREATE ALIAS DEPT FOR DEPARTMENT;
....

====  EMPLOYEE

.EMPLOYEE sample table – DDL
[source,sql]
....
CREATE TABLE EMPLOYEE
( EMPNO     CHARACTER(6) NOT NULL
, FIRSTNME  VARCHAR(12)  NOT NULL
, MIDINIT   CHARACTER(1)
, LASTNAME  VARCHAR(15)  NOT NULL
, WORKDEPT  CHARACTER(3)
, PHONENO   CHARACTER(4)
, HIREDATE  DATE
, JOB       CHARACTER(8)
, EDLEVEL   SMALLINT     NOT NULL
, SEX       CHARACTER(1)
, BIRTHDATE DATE
, SALARY    DECIMAL(9, 2)
, BONUS     DECIMAL(9, 2)
, COMM      DECIMAL(9, 2))
IN USERSPACE1;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPNO);

CREATE INDEX XEMP2
ON EMPLOYEE(WORKDEPT ASC)
ALLOW REVERSE SCANS;

CREATE ALIAS EMP FOR EMPLOYEE;
....

====  EMPMDC

.EMPMDC sample table – DDL
[source,sql]
....
CREATE TABLE EMPMDC
( EMPNO INTEGER
, DEPT  INTEGER
, DIV   INTEGER)
IN IBMDB2SAMPLEREL;
....

====  EMPPROJACT

.EMPPROJACT sample table – DDL
[source,sql]
....
CREATE TABLE EMPPROJACT
( EMPNO    CHARACTER(6) NOT NULL
, PROJNO   CHARACTER(6) NOT NULL
, ACTNO    SMALLINT     NOT NULL
, EMPTIME  DECIMAL(5, 2)
, EMSTDATE DATE
, EMENDATE DATE)
IN USERSPACE1;

CREATE ALIAS EMP_ACT FOR EMPPROJACT;
CREATE ALIAS EMPACT FOR EMPPROJACT;
....

====  EMP_PHOTO

.EMP_PHOTO sample table – DDL
[source,sql]
....
CREATE TABLE EMP_PHOTO
( EMPNO        CHARACTER(6)  NOT NULL
, PHOTO_FORMAT VARCHAR(10)   NOT NULL
, PICTURE      BLOB(102400)
, EMP_ROWID    CHARACTER(40) NOT NULL)
IN USERSPACE1;

ALTER TABLE EMP_PHOTO
ADD CONSTRAINT PK_EMP_PHOTO PRIMARY KEY(EMPNO, PHOTO_FORMAT);
....

====  EMP_RESUME

.EMP_RESUME sample table – DDL
[source,sql]
....
CREATE TABLE EMP_RESUME
( EMPNO CHARACTER(6) NOT NULL
, RESUME_FORMAT VARCHAR(10) NOT NULL
, RESUME CLOB(5120)
, EMP_ROWID CHARACTER(40) NOT NULL)
IN USERSPACE1;

ALTER TABLE EMP_RESUME
ADD CONSTRAINT PK_EMP_RESUME PRIMARY KEY(EMPNO, RESUME_FORMAT);
....

====  IN_TRAY

.IN_TRAY sample table – DDL
[source,sql]
....
CREATE TABLE IN_TRAY
( RECEIVED TIMESTAMP
, SOURCE CHARACTER(8)
, SUBJECT CHARACTER(64)
, NOTE_TEXT VARCHAR(3000))
IN USERSPACE1;
....

.INVENTORY sample table – DDL
[source,sql]
....
CREATE TABLE INVENTORY
( PID VARCHAR(10) NOT NULL
, QUANTITY INTEGER
, LOCATION VARCHAR(128))
IN IBMDB2SAMPLEXML;

ALTER TABLE INVENTORY
ADD CONSTRAINT PK_INVENTORY PRIMARY KEY(PID);
....

====  ORG

.ORG sample table – DDL
[source,sql]
....
CREATE TABLE ORG
( DEPTNUMB SMALLINT NOT NULL
, DEPTNAME VARCHAR(14)
, MANAGER SMALLINT
, DIVISION VARCHAR(10)
, LOCATION VARCHAR(13))
IN USERSPACE1;
....

====  PRODUCT

.PRODUCT sample table – DDL
[source,sql]
....
CREATE TABLE PRODUCT
( PID VARCHAR(10) NOT NULL
, NAME VARCHAR(128)
, PRICE DECIMAL(30,2)
, PROMOPRICE DECIMAL(30, 2)
, PROMOSTART DATE
, PROMOEND DATE
, DESCRIPTION XML)
IN IBMDB2SAMPLEXML;

ALTER TABLE PRODUCT
ADD CONSTRAINT PK_PRODUCT PRIMARY KEY(PID);
....

====  PRODUCTSUPPLIER

.PRODUCTSUPPLIER sample table – DDL
[source,sql]
....
CREATE TABLE PRODUCTSUPPLIER
( PID VARCHAR(10) NOT NULL
, SID VARCHAR(10) NOT NULL)
IN IBMDB2SAMPLEXML;
....

====  PROJACT

.PROJACT sample table – DDL
[source,sql]
....
CREATE TABLE PROJACT
( PROJNO CHARACTER(6) NOT NULL
, ACTNO SMALLINT NOT NULL
, ACSTAFF DECIMAL(5, 2)
, ACSTDATE DATE NOT NULL
, ACENDATE DATE)
IN USERSPACE1;

ALTER TABLE PROJACT
ADD CONSTRAINT PK_PROJACT PRIMARY KEY(PROJNO, ACTNO, ACSTDATE);
....

====  PROJECT

.PROJECT sample table – DDL
[source,sql]
....
CREATE TABLE PROJECT
( PROJNO CHARACTER(6) NOT NULL
, PROJNAME VARCHAR(24) NOT NULL
, DEPTNO CHARACTER(3) NOT NULL
, RESPEMP CHARACTER(6) NOT NULL
, PRSTAFF DECIMAL(5, 2)
, PRSTDATE DATE
, PRENDATE DATE
, MAJPROJ CHARACTER(6))
IN USERSPACE1;

ALTER TABLE PROJECT
ADD CONSTRAINT PK_PROJECT PRIMARY KEY(PROJNO);

CREATE INDEX XPROJ2
ON PROJECT(RESPEMP ASC)
ALLOW REVERSE SCANS;

CREATE ALIAS PROJ FOR PROJECT;
....

====  PURCHASEORDER

.PURCHASEORDER sample table – DDL
[source,sql]
....
CREATE TABLE PURCHASEORDER
( POID BIGINT NOT NULL
, STATUS VARCHAR(10) NOT NULL
, CUSTID BIGINT
, ORDERDATE DATE
, PORDER XML
, COMMENTS VARCHAR(1000))
IN IBMDB2SAMPLEXML;

ALTER TABLE PURCHASEORDER
ADD CONSTRAINT PK_PURCHASEORDER PRIMARY KEY(POID);
....

====  SALES

.SALES sample table – DDL
[source,sql]
....
CREATE TABLE SALES
( SALES_DATE DATE
, SALES_PERSON VARCHAR(15)
, REGION VARCHAR(15)
, SALES INTEGER)
IN USERSPACE1;
....

====  STAFF

.STAFF sample table – DDL
[source,sql]
....
CREATE TABLE STAFF
( ID SMALLINT NOT NULL
, NAME VARCHAR(9)
, DEPT SMALLINT
, JOB CHARACTER(5)
, YEARS SMALLINT
, SALARY DECIMAL(7, 2)
, COMM DECIMAL(7,2))
IN USERSPACE1;
....

====  SUPPLIERS

.SUPPLIERS sample table – DDL
[source,sql]
....
CREATE TABLE SUPPLIERS
( SID VARCHAR(10) NOT NULL
, ADDR XML)
IN IBMDb2SAMPLEXML;

ALTER TABLE SUPPLIERS
ADD CONSTRAINT PK_PRODUCTSUPPLIER PRIMARY KEY(SID);
....


